log_format detailed '$remote_addr - $remote_user [$time_local] '
                    '"$request_method $request_uri $server_protocol" '
                    '$status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" '
                    'rt=$request_time';

access_log /var/log/nginx/access.log detailed;
error_log  /var/log/nginx/error.log warn;

server {
    # observe all traffic to this point
    listen 80 default_server;
    server_name _; # do not have a proper hostname

    # point to where to serve files from
    root /app/frontend;
    index index.html;

    client_max_body_size 5m;

    # reverse proxy to backend
    location /api/ {
        client_max_body_size 15m;
        proxy_pass http://localhost:8888/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # handle front-end
    location / {
        try_files $uri $uri/ /index.html;
    }

    # deny secret files
    location ~ /\. {
        deny all;
    }

    autoindex off;
}